import time
value =  0

# The part to get the ores of the player
print("--Low Blues--")
bean = input("# of Jellybeanite?")
TIS = input("# of This Is Stone?")
MS = input("# of Meme Stone?")
OS = input("# of Old spinel?")
Gr = input("# of Grandidierite?")
print("--Middle Blues--")
Li = input("# of Limitium?")
Ba = input("# of Bassium?")
Ne = input("# of Nevadaite?")
C = input("# of Caelum?")
Co = input("# of Coruscent?")
Col = input("# of Col?")
Va = input("# of Vanadinite?")
Xa = input("# of Xanthiosite?")
print("--High Blues--")
Vi = input("# of Viridescent?")
Pu = input("# of Perpetuum?")
So = input("# of Somnium?")
Qe = input("# of Qekqe?")
print("--Low Reds--")
Qc = input("# of Qcffidhsr?")
Lc = input("# of Lckzdrkv?")
Ga = input("# of Gamingfishite?")
As = input("# of Astatine?")
Oc = input("# of Occultatum?")
VC = input("# of Vaporwave Crystal?")
Zn = input("# of Znynpuvgr?")
print("--Middle Reds--")
Fr = input("# of Fracture?")
Nd = input("# of Ndawqz?")
Cl = input("# of Clockwork?")
Dw = input("# of Dwywfvsjq?")
Gl = input("# of Glitched?")
Ty = input("# of Tyvqpurg?")
MD = input("# of Mysterious Dumortierite?")
print("--High Reds--")
An = input("# of Anomaly?")
Ho = input("# of Hollow?")
Or = input("# of Origin?")
Et = input("# of Eternal?")
Dm = input("# of Dumazai?")
print("--Low purples--")
On = input("# of Onion?")
An = input("# of Antimatter?")
LuC = input("# of Lucky Clover?")
print("--Middle purples--")
Le = input("# of Leek?")
DM = input("# of Dark matter?")
Br = input("# of Bread?")
Mi = input("# of Missing?")
print("--High purples--")
NT = input("# of No Texture?")
Ro= input("# of Rock?")
Ul = input("# of Ultimate Baseite?")
Ic = input("# of Ice cube?")
print("--Pinks--")
Di = input("# of Dirt?")
Grass = input("# of Grass?")
Vo = input("# of Void?")
Ab = input("# of Abyss?")
And = input("# of Andromeda?")
print("--Gilded--")
Gj = input("# of Gilded Jellybeanite?")
Gt = input("# of Gilded This is Stone?")
Gm = input("# of Gilded Meme stone?")
Go = input("# of Gilded Old spinel")
Gildedgrand = input("# of Gilded Grandidierite?")
Gl = input("# of Gilded Limitium?")
Gb = input("# of Gilded Bassium?")
print("--Event--")
k = input("# of Colourful eggstone, and Frosted Jellybeanite?")
M = input("# of Cakeium, Fireworkite, Pot of gold, Malachite heart, Easter eggstone, Fools Znynpuvgr, Fools Dwywfvsjq, Glitched eggstone, Pumpkin Malachite, Frosted Grandidierite, and Victoria Sponge Cakeium?")
MMkkkkk = input("# of Magicial Eggstone?")
MMMMM = input("# of Eggstone King, Golden eggstone, and Frosted gamingfishite?")

# The part that calculates the value

value = value + (int(bean) * 100)
value = value + (int(TIS) * 250)
value = value + (int(MS) * 700)
value = value + (int(Gr) * 1000)
value = value + (int(Li) * 1500)
value = value + (int(Ba) * 2000)
value = value + (int(Ne) * 3000)
value = value + (int(C) * 4000)
value = value + (int(Co) * 5000)
value = value + (int(Col) * 6000)
value = value + (int(Va) * 7000)
value = value + (int(Xa) * 8500)
value = value + (int(Vi) * 10000)
value = value + (int(Pu) * 11000)
value = value + (int(So) * 12000)
value = value + (int(Qe) * 14000)
value = value + (int(Qc) * 15000)
value = value + (int(Lc) * 18000)
value = value + (int(Ga)* 20000)
value = value + (int(As) * 23000)
value = value + (int(Oc) * 25000)
value = value + (int(VC) * 27000)
value = value + (int(Zn) * 30000)
value = value + (int(Fr) * 35000)
value = value + (int(Nd) * 40000)
value = value + (int(Cl) * 45000)
value = value + (int(Dw) * 50000)
value = value + (int(Gl) * 58000)
value = value + (int(Ty) * 60000)
value = value + (int(MD) * 65000)
value = value + (int(An) * 70000)
value = value + (int(Ho) * 75000)
value = value + (int(Or) * 80000)
value = value + (int(Et) * 85000)
value = value + (int(Dm) * 90000)
value = value + (int(On) * 100000)
value = value + (int(An) * 150000)
value = value + (int(LuC) * 250000)
value = value + (int(Le) * 350000)
value = value + (int(DM) * 400000)
value = value + (int(Br) * 500000)
value = value + (int(Mi) * 600000)
value = value + (int(NT) * 750000)
value = value + (int(Ro) * 800000)
value = value + (int(Ul) * 850000)
value = value + (int(Ic) * 900000)
value = value + (int(Di) * 1000000)
value = value + (int(Grass) * 1250000)
value = value + (int(Vo) * 1500000)
value = value + (int(Ab) * 2000000)
value = value + (int(And) * 3000000)
value = value + (int(Gj) * 10000)
value = value + (int(Gt) * 25000)
value = value + (int(Gm) * 50000)
value = value + (int(Go) * 70000)
value = value + (int(Gildedgrand) * 100000)
value = value + (int(Gl) * 150000)
value = value + (int(Gb) * 200000)
value = value + (int(k) * 100)
value = value + (int(M) * 1000)
value = value + (int(MMkkkkk) * 2500)
value = value + (int(MMMMM) * 5000)

#print it out

print("Your value is " + str(int(value) / 1000) + " Million.")

time.sleep(250)



